name: gh-pages

on:
  push:
    branches:
      - gh-pages

jobs:

  bump-version:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN_ACTION }}

    - name: Setup GIT
      run: |
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config user.name "$GITHUB_ACTOR"

    - name: Build Project Lib
      run: |
        git fetch
        git checkout ${{ github.head_ref }}
        cd projects/angular-boost-kit/
        ng build

    - name: Build App
      run: |
        cd ../../
        ng build --base-href="https://betorobson.github.io/angular-boost-kit/"
        rm -rf ./docs
        mv dist/angular-boost-kit-app/browser ./docs

    - name: Commit Build
      run: |
        get add -A
        git commit -am 'gh-pages'
        git push origin ${{ github.head_ref }}
